version: "3.9"
services:
  server:
    build: ./infra/server
    ports:
      - "8080:80"
    env_file:
      - "./.env.dev"
    tty: true
  golang:
    build: ./infra/golang
    volumes:
      - "./infra/server/build:/go/build"
      - "./src/app:/go/src"
    ports:
      - "3080:80"
    environment:
      - APPROOT=/go/src
    env_file:
      - "./.env.dev"
    tty: true
  redis:
    build: ./infra/redis
    expose:
      - "6379"
